"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  AlertTriangle,
  Bell,
  CheckCheck,
  MessageSquare,
  ShoppingBag,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";
import { AdminPage, AdminPageHeader } from "@/apps/admin/components";
import { DashboardStatCard } from "@/apps/admin/dashboard/components/dashboard-stat-card";
import {
  FilterPanel,
  FilterPanelSearch,
  FilterPanelToolbar,
} from "@/apps/admin/components/filter-panel";
import { EmptyState } from "@/components/shared/empty-state";
import { ListLoading } from "@/components/shared/list-loading";
import { ListPagination } from "@/components/shared/list-pagination";
import { NotificationListItem } from "@/apps/admin/commerce/components/notification-list-item";
import {
  defaultNotificationFilters,
  filterNotifications,
  formatNotificationType,
  groupNotificationsByDay,
} from "@/apps/admin/commerce/lib/notification-utils";
import {
  buildNotificationOverview,
  clearReadNotifications,
  defaultNotificationSettings,
  dismissNotification,
  getNotificationSettings,
  markAllNotificationsRead,
  markNotificationRead,
  saveNotificationSettings,
  syncNotifications,
} from "@/apps/admin/commerce/lib/notifications-repository";
import { subscribeToAdminData } from "@/apps/admin/lib/admin-data-events";
import {
  isWeddingEnabled,
  SETTINGS_UPDATED_EVENT,
} from "@/features/settings/lib/settings-repository";
import type {
  AdminNotification,
  NotificationListFilters,
  NotificationSettings,
  NotificationType,
} from "@/types/notification";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AdminSelect } from "@/apps/admin/products/components/admin-field";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";
import { reportedAsSignedOut } from "@/apps/admin/lib/report-write";
import { useOrdersServerSync } from "@/features/orders/lib/use-orders-server-sync";

const PAGE_SIZE = 12;

/**
 * Every kind this page can produce.
 *
 * refund_request, gateway_error and cod_confirmation were generated by the
 * repository and missing from this list, so an admin could not filter to them
 * and no card counted them — a refund request sat in the feed with no way to
 * reach it except scrolling.
 */
const typeOptions = [
  "all",
  "order_placed",
  "payment_received",
  "payment_failed",
  "refund_request",
  "cod_confirmation",
  "gateway_error",
  "low_stock",
  "out_of_stock",
  "inquiry_new",
  "system",
] as const;

const preferenceItems = [
  {
    key: "orderAlerts" as const,
    label: "New orders",
    description: "Orders from the last 30 days",
  },
  {
    key: "paymentAlerts" as const,
    label: "Payments",
    description: "Online payments received or failed",
  },
  {
    key: "stockAlerts" as const,
    label: "Stock alerts",
    description: "Low stock and out-of-stock products",
  },
  {
    key: "inquiryAlerts" as const,
    label: "Inquiries",
    description: "Contact, wedding, and newsletter",
  },
];

export function NotificationsAdminPage() {
  /**
   * This screen's own data, asked for NOW.
   *
   * The admin layout hydrates every admin cache — this one included — but only
   * after `useIdle(1000)`, so that the screen the admin opened gets the
   * connection first. For a screen whose content IS one of those caches that is
   * backwards: it spent that second waiting on a delay meant to help it.
   *
   * Mounting the same hook here costs nothing — `hydrateOnce` makes the
   * layout's later call join this read rather than repeat it — and the rest of
   * the batch still waits its turn.
   */
  useOrdersServerSync();

  const [weddingEnabled, setWeddingEnabled] = useState(true);

  useEffect(() => {
    const sync = () => setWeddingEnabled(isWeddingEnabled());
    sync();
    window.addEventListener(SETTINGS_UPDATED_EVENT, sync);
    return () => window.removeEventListener(SETTINGS_UPDATED_EVENT, sync);
  }, []);
  const [filters, setFilters] = useState<NotificationListFilters>(defaultNotificationFilters);
  const [page, setPage] = useState(1);
  const [loadedNotifications, setNotifications] = useState<AdminNotification[] | null>(null);
  /**
   * `null` until the first derivation has run — the absence IS the signal, so
   * there is no second piece of state and nothing extra to set in the effect.
   *
   * Notifications are DERIVED from orders, inquiries and inventory rather than
   * stored, and those stores are filled by the admin layout after mount. So on
   * a cold load the derivation ran over empty inputs and the page said "No
   * notifications" to a shop with pending orders and low stock.
   */
  const loaded = loadedNotifications !== null;
  // Memoised: this feeds two `useMemo`s below, and a fresh `[]` on every render
  // would make both of them recompute forever.
  const notifications = useMemo(() => loadedNotifications ?? [], [loadedNotifications]);
  const [settings, setSettings] = useState<NotificationSettings>(defaultNotificationSettings);
  const [savedSettings, setSavedSettings] = useState<NotificationSettings>(
    defaultNotificationSettings
  );
  const [saving, setSaving] = useState(false);

  // Counted from the same snapshot the list renders, so the cards can never
  // disagree with what is below them.
  const overview = useMemo(() => buildNotificationOverview(notifications), [notifications]);
  const filtered = useMemo(
    () => filterNotifications(notifications, filters),
    [notifications, filters]
  );
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const currentPage = Math.min(page, totalPages);
  const paginated = filtered.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);
  const grouped = useMemo(() => groupNotificationsByDay(paginated), [paginated]);
  const settingsDirty = JSON.stringify(settings) !== JSON.stringify(savedSettings);

  // Read the live dirty flag inside the listener without making it an effect
  // dependency — the effect subscribes once, but must see the current value.
  const settingsDirtyRef = useRef(settingsDirty);
  useEffect(() => {
    settingsDirtyRef.current = settingsDirty;
  }, [settingsDirty]);

  useEffect(() => {
    function refresh() {
      setNotifications(syncNotifications());

      // Server hydration lands after mount. Adopting its preferences then would
      // silently discard toggles the admin has flipped but not saved yet.
      if (settingsDirtyRef.current) return;
      const loaded = getNotificationSettings();
      setSettings(loaded);
      setSavedSettings(loaded);
    }

    refresh();
    return subscribeToAdminData(refresh);
  }, []);

  function updateFilters(patch: Partial<NotificationListFilters>) {
    setFilters((prev) => ({ ...prev, ...patch }));
    setPage(1);
  }

  function filterByType(type: NotificationListFilters["type"]) {
    updateFilters({ type, status: "all", search: "" });
  }

  function bump() {
    setNotifications(syncNotifications());
  }

  async function handleSaveSettings() {
    setSaving(true);
    const persisted = await saveNotificationSettings(settings);
    setSaving(false);
    bump();

    if (!persisted) {
      // Applied locally, but the server refused it — say so rather than leaving
      // the admin to discover on another device that the toggle never stuck.
      if (!reportedAsSignedOut()) toast.error("Applied on this device only — the server rejected the change.");
      return;
    }

    setSavedSettings(settings);
    toast.success("Notification preferences saved");
  }

  return (
    <AdminPage className="space-y-4 sm:space-y-5">
      <AdminPageHeader
        title="Notifications"
        description="Orders, payments, stock, and inquiry alerts."
        className="gap-3"
        actions={
          <div className="flex w-full gap-2">
            <Button
              variant="outline"
              className="min-w-0 flex-1 sm:flex-none"
              onClick={() => {
                const cleared = clearReadNotifications();
                bump();
                toast.success(
                  cleared > 0 ? `Cleared ${cleared} read alert(s)` : "No read alerts to clear"
                );
              }}
            >
              <Trash2 className="size-4" />
              <span className="sm:hidden">Clear</span>
              <span className="hidden sm:inline">Clear read</span>
            </Button>
            <Button
              variant="bakery"
              className="min-w-0 flex-1 sm:flex-none"
              onClick={() => {
                markAllNotificationsRead();
                bump();
                toast.success("All notifications marked as read");
              }}
              disabled={overview.unread === 0}
            >
              <CheckCheck className="size-4" />
              <span className="sm:hidden">Mark read</span>
              <span className="hidden sm:inline">Mark all read</span>
            </Button>
          </div>
        }
      />

      <section className="grid grid-cols-2 gap-2.5 sm:gap-3 xl:grid-cols-4">
        <button
          type="button"
          className="h-full w-full rounded-xl text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          onClick={() => updateFilters({ status: "unread", type: "all", search: "" })}
        >
          <DashboardStatCard
            title="Unread"
            value={overview.unread}
            change={overview.unread > 0 ? "Needs attention" : "All clear"}
            changeTone={overview.unread > 0 ? "warning" : "positive"}
            icon={Bell}
            tone="gold"
          />
        </button>
        <button
          type="button"
          className="h-full w-full rounded-xl text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          onClick={() => filterByType("order_placed")}
        >
          <DashboardStatCard
            title="Orders"
            value={overview.orderCount}
            change="New order alerts"
            changeTone="neutral"
            icon={ShoppingBag}
            tone="bakery"
          />
        </button>
        <button
          type="button"
          className="h-full w-full rounded-xl text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          // Counts low_stock + out_of_stock, so it filters to both. It used to
          // filter to low_stock alone, hiding exactly the products that cannot
          // be sold at all.
          onClick={() => filterByType("stock_alerts")}
        >
          <DashboardStatCard
            title="Stock"
            value={overview.stockCount}
            change={overview.stockCount > 0 ? "Needs restock" : "Stock healthy"}
            changeTone={overview.stockCount > 0 ? "warning" : "positive"}
            icon={AlertTriangle}
            tone="bakery"
          />
        </button>
        <button
          type="button"
          className="h-full w-full rounded-xl text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          onClick={() => filterByType("inquiry_new")}
        >
          <DashboardStatCard
            title="Inquiries"
            value={overview.inquiryCount}
            change="Customer messages"
            changeTone="neutral"
            icon={MessageSquare}
            tone="bakery"
          />
        </button>
      </section>

      <div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(240px,300px)]">
        <div className="min-w-0 space-y-4">
          <FilterPanel>
            <FilterPanelToolbar className="gap-2.5 sm:flex-row sm:items-center">
              <FilterPanelSearch
                value={filters.search}
                onChange={(value) => updateFilters({ search: value })}
                placeholder="Search notifications..."
              />
              <div className="grid grid-cols-2 gap-2 sm:flex sm:shrink-0">
                <AdminSelect
                  className="w-full sm:w-36"
                  value={filters.status}
                  onChange={(event) =>
                    updateFilters({
                      status: event.target.value as NotificationListFilters["status"],
                    })
                  }
                  aria-label="Notification status"
                >
                  <option value="all">All status</option>
                  <option value="unread">Unread</option>
                  <option value="read">Read</option>
                </AdminSelect>
                <AdminSelect
                  className="w-full sm:w-44"
                  value={filters.type}
                  onChange={(event) =>
                    updateFilters({
                      type: event.target.value as NotificationListFilters["type"],
                    })
                  }
                  aria-label="Notification type"
                >
                  {typeOptions.map((type) => (
                    <option key={type} value={type}>
                      {type === "all" ? "All types" : formatNotificationType(type)}
                    </option>
                  ))}
                </AdminSelect>
              </div>
            </FilterPanelToolbar>
          </FilterPanel>

          {!loaded ? (
            <ListLoading rows={4} label="Loading notifications" />
          ) : filtered.length === 0 ? (
            <EmptyState
              icon={Bell}
              title="No notifications"
              description="Alerts matching your filters will appear here."
            />
          ) : (
            <div className="space-y-5">
              {grouped.map((group) => (
                <section key={group.label} className="space-y-2.5">
                  <h2 className="text-[11px] font-semibold tracking-wider text-muted-foreground uppercase">
                    {group.label}
                  </h2>
                  <div className="space-y-2.5">
                    {group.items.map((notification) => (
                      <NotificationListItem
                        key={notification.id}
                        notification={notification}
                        onMarkRead={(id) => {
                          markNotificationRead(id);
                          bump();
                        }}
                        onDismiss={(id) => {
                          dismissNotification(id);
                          bump();
                          toast.success("Notification dismissed");
                        }}
                      />
                    ))}
                  </div>
                </section>
              ))}

              <ListPagination
                currentPage={currentPage}
                totalPages={totalPages}
                onPageChange={setPage}
              />
            </div>
          )}
        </div>

        <Card className="h-fit shadow-sm lg:sticky lg:top-24">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Alert preferences</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2.5 pt-0">
            {preferenceItems.map((item) => (
              <label
                key={item.key}
                className={cn(
                  "flex cursor-pointer items-center justify-between gap-3 rounded-lg border border-border px-3 py-2.5",
                  "transition-colors hover:border-border"
                )}
              >
                <div className="min-w-0">
                  <p className="text-sm font-medium">{item.label}</p>
                  <p className="text-xs text-muted-foreground">
                    {item.key === "inquiryAlerts" && !weddingEnabled
                      ? "Contact and newsletter"
                      : item.description}
                  </p>
                </div>
                <Switch
                  checked={settings[item.key]}
                  onCheckedChange={(checked) =>
                    setSettings((prev) => ({ ...prev, [item.key]: checked === true }))
                  }
                />
              </label>
            ))}

            <Button
              variant="bakery"
              className="w-full"
              onClick={handleSaveSettings}
              disabled={!settingsDirty || saving}
            >
              {saving ? "Saving..." : "Save preferences"}
            </Button>
          </CardContent>
        </Card>
      </div>
    </AdminPage>
  );
}
